apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  labels:
    app: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: local/supabase-test/postgrest:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PGRST_DB_URI
              value: "postgresql://devuser:devpassword@postgres:5432/appdb"
            - name: PGRST_DB_SCHEMAS
              value: "public"
            - name: PGRST_DB_ANON_ROLE
              value: "devuser"
            - name: PGRST_SERVER_PORT
              value: "3000"
