apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: local/supabase-test/web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: POSTGREST_URL
              value: "http://postgrest:3000"
            - name: NODE_ENV
              value: "development"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
